### ISSUE TITLE
do not work with current u2fval server

### ISSUE THREAD

**Issue by hudecof** [dainnilsson/flask-u2f-tutorial#3]
seems that there are some changes in API in current u2fval server ad this demo is not working anymore.

For example:
 - in **u2f_add.html** the `reg_req.authenticateRequests` is **Undefined**. 

Would it be possoble to fix it to work with actual u2fval 2.0.0 server?

**Comment by dainnilsson** [comment]
This is resolved by PR #4, right?

**Comment by hudecof** [comment]
yes, but please check the code. It workson my laptom with all treee browsers.
